name: Terraform Deploy Caller Example (Apply on PR)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/terraform-deploy.yaml
    with:
      terraform_version: 1.9.8
      working_directory: infra
      tf_var_file: env/dev.tfvars
      backend_config_file: env/dev.tfbackend
      apply_on_pr: true
      apply_on_merge: true
      apply_environment: dev
      artifact_retention_days: 7
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
