name: Terraform Deploy Caller

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/terraform-deploy.yaml
    with:
      terraform_version: 1.9.8
      working_directory: terraform
      tf_var_file: env/dev/dev.tfvars
      backend_config_file: env/dev/dev.tfbackend
      apply_on_pr: false
      apply_on_merge: true
      artifact_retention_days: 7
      azure_client_id: ${{ vars.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ vars.AZURE_TENANT_ID }}